name: deploy-production

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
      
    - name: Publish to Docker2
      uses: dennyabrain/docker-action@master
      with:
        username: tattletech
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tattletech/archive-server
        tag: stable
        arg1: ${{ secrets.AWS_ACCESS_KEY_ID }}
        arg2: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to k8s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST_PROD }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_KEY }}
          script: |
            ./autodeploy_kosh_rest.sh.sh ${{ steps.vars.outputs.sha_short }} >> ~/deploy.log 2>&1

      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deployed Kosh to staging environment"
          SLACK_TITLE: "staging-deploy workflow complete"
          SLACK_COLOR: "#020637"
          SLACK_ICON: https://tattle-media.s3.amazonaws.com/monogram-dark.svg
    
    
    
    
    
    
    
    
    
